### ISSUE TITLE
Transformer vs CNN based architectures

### ISSUE THREAD

**Issue by ArielReplicate** [anguyen8/gScoreCAM#4]
Hi,
Thanks for uploading the codes for this wonderful project. It can really help us understand and debug the feature space of CLIP.

The model seem to work very well with CNN based CLIP but not as good with ViT architecture?
Is this normal?
Here are my outputs for RN50x16 and ViT-B/32 for the example image in this repo
I'm running both with 
`topk=300  and  cam_version='gscorecam' and input_text="Heart"
`
| RN50x16   | ViT-B/32 |
|----------|:-------------:|
|<img src="https://user-images.githubusercontent.com/116253211/213697256-5904de14-8ffa-43b3-9b45-ef68a7513c97.png" alt="drawing" width="200"/> | <img src="https://user-images.githubusercontent.com/116253211/213697266-43669ea2-3747-450e-abbe-8513a4bdf1a0.png" alt="drawing" width="200"/> |

Should ViT models work as well? Do they need other settings?

**Comment by Chanfeechen** [comment]
Thank you for your interest. Since the method relies on the channels in CNN, the approach we applied to ViT is not optimal. Here are two ways may get better results on ViT:
1. Adjust the k. i.e., in ViT-B/32 there are only 768 channels, but in RNx16, there are 3072 channels. So a smaller number `k=100` will result in a less noisy output for ViT-B/32. 
2. Use a larger model of ViT variance. e.g., `ViT-B/16`.

**Comment by ArielReplicate** [comment]
Thanks for the help.
I tried ViT-B/32 with k=100 and didn't get good results. should it be different with ViT-B/16
Also Is there a significant difference between the different ResNet backbones ? I'm using mostly RN50x16

**Comment by Chanfeechen** [comment]
For ViT-B/16, you should have slightly different results but I will expect there are similar. 
For the difference in the backbone, in terms of interpretability, RNx4 and RNx16 are similar. But the RNx16 backbone has better performance in terms of prediction.
